### ISSUE TITLE
Permanent background process

### ISSUE THREAD

**Issue by dmitriigaidarji** [mac-cain13/notificato#42]
Can you share your thoughts what is the best way to implement the permanent process of checking for newly added notifications and occasionally sending the new ones with your "Notificato"? Currently i am using php module "memory cache", but i wonder if i missed something and there is a better solution.

**Comment by jamesrgrinter** [comment]
I am using Gearman and "mmoreram/gearman-bundle", but I am still really in very early stages of learning the best way to configure and use Gearman processes across multiple machines and its queue.

(But I think one of my problems - if I leave it running for some time, then messages stop being sent - is a notificato issue that will be addressed when I update to 1.1.1, as it looks like it's a loss of the TCP connection to Apple.)

**Comment by mac-cain13** [comment]
Gearman is nice or any message broker system of choice could be used. 

Often I just create a PHP file that keeps running and checks a MySQL database, using [Daemonizable Commands for Symfony2](https://github.com/mac-cain13/daemonizable-command).
