### ISSUE TITLE
Add category field

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/notificato#45]
This is quite an important field you can't set right now.

Suggested in https://github.com/mac-cain13/notificato/pull/44

**Comment by chekalskiy** [comment]
When you will resolve this issue and release a new version? :-)

**Comment by mac-cain13** [comment]
I've just released version 1.1.2 with the category field support and your bugfix from PR #44! :)

**Comment by chekalskiy** [comment]
Thank you!
