### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by pedro380085** [mac-cain13/notificato#49]
Hi,

Everytime I execute the function, I get:
```
Fatal error: Maximum execution time of 30 seconds exceeded in ..../Wrep/Notificato/Apns/Gateway.php on line 173
```

The push notification is sent, but the server code never resumes. It just keeps running until our server maximum settings.

**Comment by mac-cain13** [comment]
Thanks for using Notificato!

Can you show me what function you execute in what way? Some code would be really useful!

Some other questions that could help me see what's going on:
- Are the examples in the Readme working for you or not?
- When you (temporary) raise the time limit, does it return or give an error then?
- Is the push notification received by the iOS device?

**Comment by pedro380085** [comment]
Hi @mac-cain13 ,

- I'm using the The full blown example, as specified on push.md. The only thing I did was to change variables to reflect my device token.
- If I raise the limit, issue still persists.
- Yes, it is received.

I believe is some kind of error on Apple servers.

Thank you,

**Comment by pedro380085** [comment]
Any news on that @mac-cain13 ?

**Comment by pedro380085** [comment]
I stopped using the library, it doesn't work for me.

**Comment by mac-cain13** [comment]
Sad to hear and sorry to see your go! I can't reproduce the issue over here, want to look further into it, but I'm short on time at this moment.

Hope you can find a good working solutions for your pushnotifications!

**Comment by pedro380085** [comment]
Solved!

**Comment by mac-cain13** [comment]
What solved it for you? Another lib or something fixed in this lib?

**Comment by pedro380085** [comment]
A crazy long execution time (5 minutes).

**Comment by mac-cain13** [comment]
Alright, thanks for letting me know!
