### ISSUE TITLE
How to add the custom information with the push notification?

### ISSUE THREAD

**Issue by manifsp** [mac-cain13/notificato#56]
I am sending push notifications from php job application to iphone. I am sending push notifications regarding new jobs. Is this possible that when user click on the view of push notification pop up , then user redirect to the particular job in the device.

I mean I wanted to know can I send any custom data with push notification like access_token,   something else....so that Iphone end Can retrieve and show the particular job ?

Regardless of the language and library you use, the push notification payload is a JSON payload:
{
    "aps": {
         "badge": 10,
         "alert": "Hello world!",
         "sound": "cat.caf"
    }
}

We want add custom information with the push notification. Like below

{
    "aps": {
         "badge": 10,
         "alert": "Hello world!",
         "sound": "cat.caf"
    },
    "access_token": 1
}

Thanks.

**Comment by mac-cain13** [comment]
You could use the `setPayload()` method: https://github.com/mac-cain13/notificato/blob/master/src/Wrep/Notificato/Apns/MessageBuilder.php#L215-L226

Would that answer your question?

**Comment by manifsp** [comment]
Yes, Now I'm getting the access_token with push notification. Thanks for your great support and fastest reply.
