### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Wrep\Notificato\Apns\Exception\InvalidCertificateException' with message 'Could not detect APNS environment based on the CN string

### ISSUE THREAD

**Issue by northkode** [mac-cain13/notificato#60]
is this because of the new way production certificates are created with apple apns.. no longer is there a dev or product there all under one umbrella now

**Comment by mac-cain13** [comment]
Sounds like issue #53 to me. Are you sure you're using version 1.2.0 or newer? Since that version it should work correctly or is this another change that Apple made?
